# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bioinformatics workflow for HT-SELEX analysis
author: Kashyap Chhatbar
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 500

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Information about where the book exists on the web
repository:
  url: https://github.com/kashyapchhatbar/eme_selex  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true